import {
  GitHubIcon,
  NotionIcon,
  SlackIcon,
  LinearIcon,
  GmailIcon,
  GoogleCalendarIcon,
  VercelIcon,
  ResendIcon,
  NeonIcon,
  GitLabIcon,
  JiraIcon,
  ConfluenceIcon,
  GoogleDriveIcon,
  GoogleMeetIcon,
  MicrosoftIcon,
  AzureIcon,
  GCPIcon,
  CloudflareIcon,
  SentryIcon,
  PayPalIcon,
  TelegramIcon,
  DiscordIcon,
  TwilioIcon,
  DockerIcon,
} from '@/components/icons'
import type { ComponentType, CSSProperties } from 'react'

export interface ProviderMeta {
  name: string
  Icon: ComponentType<{ size?: number; className?: string; style?: CSSProperties }>
  color: string
  bg: string
  description: string
  tools: string[]
  authType: 'oauth2' | 'api_key' | 'none'
}

export const PROVIDERS: Record<string, ProviderMeta> = {
  github: {
    name: 'GitHub',
    Icon: GitHubIcon,
    color: '#f0f6fc',
    bg: '#161b22',
    description: 'Create issues, PRs, search code',
    tools: [
      'create_issue',
      'list_issues',
      'create_pr',
      'comment_on_issue',
      'get_repo',
      'search_code',
      'get_pr_diff',
    ],
    authType: 'oauth2',
  },
  gitlab: {
    name: 'GitLab',
    Icon: GitLabIcon,
    color: '#FC6D26',
    bg: '#1a120e',
    description: 'Projects, MRs, pipelines, issues',
    tools: [
      'list_projects',
      'get_project',
      'list_merge_requests',
      'create_merge_request',
      'list_pipelines',
      'get_pipeline',
      'list_issues',
      'create_issue',
    ],
    authType: 'oauth2',
  },
  notion: {
    name: 'Notion',
    Icon: NotionIcon,
    color: '#ffffff',
    bg: '#191919',
    description: 'Pages, databases, blocks',
    tools: ['create_page', 'query_database', 'update_block'],
    authType: 'oauth2',
  },
  slack: {
    name: 'Slack',
    Icon: SlackIcon,
    color: '#e8d44d',
    bg: '#1a1320',
    description: 'Send messages, read & search channels',
    tools: ['send_message', 'read_channel', 'search_messages'],
    authType: 'oauth2',
  },
  linear: {
    name: 'Linear',
    Icon: LinearIcon,
    color: '#5e6ad2',
    bg: '#14142b',
    description: 'Issues, status updates, search',
    tools: ['create_issue', 'update_status', 'search_issues'],
    authType: 'oauth2',
  },
  gmail: {
    name: 'Gmail',
    Icon: GmailIcon,
    color: '#ea4335',
    bg: '#1c1210',
    description: 'Send, read, search emails',
    tools: ['send_email', 'read_email', 'search_emails'],
    authType: 'oauth2',
  },
  google_calendar: {
    name: 'Google Calendar',
    Icon: GoogleCalendarIcon,
    color: '#4285f4',
    bg: '#101828',
    description: 'Events, scheduling',
    tools: ['create_event', 'list_events'],
    authType: 'oauth2',
  },
  google_drive: {
    name: 'Google Drive',
    Icon: GoogleDriveIcon,
    color: '#4285F4',
    bg: '#0d1a2d',
    description: 'Files, folders, sharing',
    tools: ['list_files', 'search_files', 'get_file', 'create_file', 'share_file', 'delete_file'],
    authType: 'oauth2',
  },
  google_meet: {
    name: 'Google Meet',
    Icon: GoogleMeetIcon,
    color: '#00897B',
    bg: '#0a1a17',
    description: 'Create & manage meetings',
    tools: ['create_meeting', 'list_meetings', 'get_meeting'],
    authType: 'oauth2',
  },
  jira: {
    name: 'Jira',
    Icon: JiraIcon,
    color: '#0052CC',
    bg: '#0a1628',
    description: 'Projects, issues, transitions',
    tools: [
      'list_projects',
      'search_issues',
      'get_issue',
      'create_issue',
      'update_issue',
      'add_comment',
      'list_transitions',
    ],
    authType: 'oauth2',
  },
  confluence: {
    name: 'Confluence',
    Icon: ConfluenceIcon,
    color: '#1868DB',
    bg: '#0d1526',
    description: 'Spaces, pages, search',
    tools: [
      'list_spaces',
      'search_content',
      'get_page',
      'create_page',
      'update_page',
      'list_pages',
    ],
    authType: 'oauth2',
  },
  microsoft: {
    name: 'Microsoft 365',
    Icon: MicrosoftIcon,
    color: '#0078D4',
    bg: '#0a1628',
    description: 'Outlook, Calendar, Teams',
    tools: [
      'list_emails',
      'send_email',
      'search_emails',
      'list_events',
      'create_event',
      'list_teams',
      'list_channels',
      'send_channel_message',
    ],
    authType: 'oauth2',
  },
  azure: {
    name: 'Azure',
    Icon: AzureIcon,
    color: '#0089D6',
    bg: '#0a1628',
    description: 'VMs, AKS, storage, functions',
    tools: [
      'list_subscriptions',
      'list_resource_groups',
      'list_vms',
      'get_vm',
      'list_aks_clusters',
      'list_storage_accounts',
      'list_functions',
    ],
    authType: 'oauth2',
  },
  gcp: {
    name: 'Google Cloud',
    Icon: GCPIcon,
    color: '#4285F4',
    bg: '#0d1a2d',
    description: 'Compute, GKE, Cloud Functions',
    tools: [
      'list_projects',
      'list_compute_instances',
      'get_compute_instance',
      'list_gke_clusters',
      'list_cloud_functions',
      'list_storage_buckets',
      'list_storage_objects',
    ],
    authType: 'api_key',
  },
  cloudflare: {
    name: 'Cloudflare',
    Icon: CloudflareIcon,
    color: '#F48120',
    bg: '#1a1208',
    description: 'DNS, Workers, zones, routes',
    tools: [
      'list_zones',
      'list_dns_records',
      'create_dns_record',
      'list_workers',
      'list_routes',
      'purge_cache',
    ],
    authType: 'api_key',
  },
  sentry: {
    name: 'Sentry',
    Icon: SentryIcon,
    color: '#362D59',
    bg: '#120f1c',
    description: 'Errors, issues, performance',
    tools: [
      'list_projects',
      'list_issues',
      'get_issue',
      'list_events',
      'resolve_issue',
      'get_event',
      'list_releases',
    ],
    authType: 'oauth2',
  },
  paypal: {
    name: 'PayPal',
    Icon: PayPalIcon,
    color: '#003087',
    bg: '#0a0d1a',
    description: 'Orders, payments, payouts',
    tools: [
      'create_order',
      'get_order',
      'capture_order',
      'list_transactions',
      'create_payout',
      'get_payout',
      'create_invoice',
      'list_invoices',
    ],
    authType: 'oauth2',
  },
  vercel: {
    name: 'Vercel',
    Icon: VercelIcon,
    color: '#ffffff',
    bg: '#111111',
    description: 'Deployments, status',
    tools: ['list_deployments', 'get_deployment'],
    authType: 'oauth2',
  },
  resend: {
    name: 'Resend',
    Icon: ResendIcon,
    color: '#00d4aa',
    bg: '#0a1a17',
    description: 'Transactional emails',
    tools: ['send_email'],
    authType: 'api_key',
  },
  postgres: {
    name: 'Neon',
    Icon: NeonIcon,
    color: '#00e599',
    bg: '#0a1a14',
    description: 'Serverless PostgreSQL queries',
    tools: ['execute_query', 'list_tables', 'describe_table', 'run_transaction', 'explain_query'],
    authType: 'api_key',
  },
  docker: {
    name: 'Docker Hub',
    Icon: DockerIcon,
    color: '#2496ED',
    bg: '#0a1628',
    description: 'Images, tags, repositories',
    tools: ['list_repos', 'list_tags', 'get_manifest', 'search_images'],
    authType: 'api_key',
  },
  telegram: {
    name: 'Telegram',
    Icon: TelegramIcon,
    color: '#26A5E4',
    bg: '#0a1828',
    description: 'Messages, chats, photos',
    tools: ['send_message', 'get_updates', 'get_chat', 'send_photo', 'get_me'],
    authType: 'api_key',
  },
  discord: {
    name: 'Discord',
    Icon: DiscordIcon,
    color: '#5865F2',
    bg: '#12132b',
    description: 'Guilds, channels, messages',
    tools: ['list_guilds', 'list_channels', 'send_message', 'get_message', 'list_messages'],
    authType: 'api_key',
  },
  twilio: {
    name: 'Twilio',
    Icon: TwilioIcon,
    color: '#F22F46',
    bg: '#1a0a0d',
    description: 'SMS, WhatsApp messaging',
    tools: ['send_sms', 'send_whatsapp', 'list_messages', 'get_message'],
    authType: 'api_key',
  },
}
